language: node_js
node_js:
- '6.1'
notifications:
  slack:
    secure: unIHyMu12VGZJyYRAN44140IZaSCipmr0ne+hGGEoQhnWXh0XhqtcJNgLBZUlM+4qiiezMe1flxGmmIWX/Wamo1LudJoATYdeL/a6Zmf6IexGaIeoLguVbvIKgl+TC5MuO+eAPeyiWD1LBe3QjqplAy8PfRc3MJeU0XdPABnrp27XYHUqG5zfCr01O7kTdNn9xw+zP23RQkgKnUNLyWC/QQMvgIftOydn5ELGChf8Hzdn8ppMrYyAnl2EN46/9IThr1GTMpOeoSTooZjTW6h/ntRkWiBfiM0VmCvaVXDJqpqTAqibMhZiBIXTyCriM+q/hioAPvCPhzvN7m8sBpzXMWVPXJM1G3wF8bYYSyZ/QQNl9yY0y0uloFkYky/nuEE/rw4a8YEf9IZCGe6Qq2JM4Q04kGCW6mQdIuIdrh8puVXHjJmNSqnmQTlOvewp4vgg2fYItMmwueibUW9X1JrnMA9ntYa5Szvnnd+9GKvUVj3WLtv6R+4cUQ6MKnZ1+kvgKBLYWRcNX1HjCVYH3tIrgbYKB1FCk05uMa+GyWbYx71KIbvvG0l6xjX3YfNTRilrWS3QJCKtwwQtKcJv04eE40iCJf0HoJRS+uYmJaV8q2872I6TOdmDtrwJhTfjLFdyHCaxbv/ib77H4dvb4LfJiJHpoUXgbdpLLbX6njPOeM=
deploy:
  provider: npm
  email: webmaster-private@kth.se
  api_key:
    secure: Sr+INfqqs7dwoISk19HgmrqVXU7Id8qGPlrVZj1bi+RZXMpDvRYlMEzARv6V/aejzyOBZ8lfamw3ShslNWAoNCRSEXJ4F2dsTnNCMwyn2y0vAqAk8Gmaicw+BJIGjq41jcJdLNin6Cz9B8fRCj98DCeN1iYZw20l3vIM0H14Ll3XEvm7RyltW7NwX69upePa6N6o8BUD3nBVcoRgiu7kjngGpGsfUsOhuUbNZfNCcAnV+GUEGJMJHWOCVSEKX5p8xcICSWYKRRRYn2RjQHD3nwRXSQRI8Y0NV1HOXvrWih5HFt6GvHC/zcus/WI9qlm9yKiRPjziM0VewauHMiziBy92ze5HkLsg4NkktID2miFoWcUVA+CqsrWCAYdrD7nh6GGBa0oaq5ttD+KUjsrYUTI/w9AKmOo+z9no5ZeD+vow/NGHzmCqmpWjJFQsRuk8FXVL0eoqX8xI3jv2hug3h+B4gd3XiOuX9fJOOeyPGKmwz030QIYfzGuJZviZxwhai7O6pqL/OQBQOP63lfrl0huJna6SXSdbG15pINMgiospjObbEDfEYsGR2AW59xsk+gidpFuIJVyoWUmRasRmFxCpOTw59WbbYuIgxO6Fi5sESHjqqygJK3ZDM6cFo2yFj6muadlJqg3vaorAOKaU3q3RfIk1F2bg+T8RIyHsv8I=
  on:
    tags: true
    repo: KTH/kth-style
