import { Page, Section, Narrative } from 'kth-style-inferno-bootstrap/docs/src/components.jsx'

export default function DropdownsPage (props) {
  return (
    <Page>
      <h1>Exempelsida rubriker och brödtext (H1)</h1>
      <h2>Lorem ipsum dolor sit (H2)</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore odit nihil minima consequatur enim quisquam, reiciendis, incidunt animi dignissimos totam ad dolores fuga, eligendi facere laudantium cumque vel! Aut, ducimus.</p>
      <h2>Lorem ipsum dolor sit (H2)</h2>
      <h3>Lorem ipsum dolor sit (H3)</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus incidunt neque nisi iusto repellendus saepe dolore, enim minima perferendis tempore, natus eveniet, mollitia officia odit cupiditate sequi ea laboriosam laudantium minus necessitatibus obcaecati id corporis aliquam nostrum! Architecto voluptatum sit quas, impedit voluptate, voluptates minus dolorum autem! Qui dicta aut eligendi excepturi. Vel aut sapiente, velit esse, iste distinctio ex totam facilis neque, dignissimos fuga? Modi quaerat atque adipisci beatae totam id nesciunt eius facilis enim perferendis, deleniti nostrum ipsum, vero quisquam consectetur distinctio. Quia quae voluptatibus sint ab aliquid facere a? Porro veritatis, laboriosam vero quis qui, quibusdam aliquam!</p>
      <h3>Lorem ipsum dolor sit (H3)</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus incidunt neque nisi iusto repellendus saepe dolore, enim minima perferendis tempore, natus eveniet, mollitia officia odit cupiditate sequi ea laboriosam laudantium minus necessitatibus obcaecati id corporis aliquam nostrum! Architecto voluptatum sit quas, impedit voluptate, voluptates minus dolorum autem! Qui dicta aut eligendi excepturi. Vel aut sapiente, velit esse, iste distinctio ex totam facilis neque, dignissimos fuga? Modi quaerat atque adipisci beatae totam id nesciunt eius facilis enim perferendis, deleniti nostrum ipsum, vero quisquam consectetur distinctio. Quia quae voluptatibus sint ab aliquid facere a? Porro veritatis, laboriosam vero quis qui, quibusdam aliquam!</p>
      <h2>Lorem ipsum dolor sit (H2)</h2>
      <h3>Lorem ipsum dolor sit (H3)</h3>
      <h4>Lorem ipsum dolor sit (H4)</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque vitae debitis, adipisci natus, accusamus alias nulla aspernatur ipsam reprehenderit nostrum praesentium earum deserunt saepe soluta necessitatibus odit, delectus quisquam quod tempora rerum a, libero quidem numquam doloribus. Quis laborum, nam. Inventore corrupti aliquid tempore, sed quae totam eveniet suscipit quaerat, culpa rem voluptate dolorum veritatis modi. Obcaecati quis laudantium, voluptatibus illum delectus non perspiciatis explicabo, ducimus, consequuntur ratione repellendus magni, voluptatem odit neque quae. Numquam dolores, eum sint quod similique at, facilis, praesentium possimus doloribus veniam architecto recusandae rem ipsam! Sed accusamus laborum voluptate beatae, et in dolore, tempore nobis sapiente laudantium ad rerum cumque cupiditate ex, perspiciatis, officia deserunt. Temporibus dolorem tempora deleniti pariatur eius suscipit sapiente numquam, facere quas quia dolore praesentium inventore nobis, atque illo quidem libero ipsum. Recusandae amet, commodi cum voluptate blanditiis officiis temporibus eos doloremque optio ad neque provident nisi voluptatum ipsam explicabo totam quis a vero maxime rerum tempora dolorem. Aspernatur, doloribus. Ad assumenda provident blanditiis quaerat rerum, repellendus eos vel ducimus quidem id expedita aliquam! Id soluta dolore sit perferendis nostrum saepe, praesentium nam, amet in optio quasi incidunt, cum esse maxime. Suscipit hic esse similique unde nemo, ut quas recusandae expedita dolore sapiente blanditiis facere aliquam quibusdam ex est odio facilis at neque voluptatibus praesentium earum dolor! Ullam id porro architecto, nostrum ducimus et odio? Aliquam cupiditate ipsa, magnam, rerum ut harum quos maiores molestiae quae, non odio minus quod temporibus doloribus recusandae dolorum itaque saepe obcaecati animi ab quaerat error, placeat nostrum eveniet. Perferendis similique consequatur non libero molestias reprehenderit ratione repudiandae blanditiis? Molestias maiores in animi delectus assumenda hic fugiat nihil quibusdam reprehenderit, dolore asperiores minus facere maxime perspiciatis rem repellat aspernatur repudiandae labore porro ipsum veniam et quas odio nisi. Eaque assumenda temporibus ex deserunt asperiores voluptate, vero.</p>
      <h4>Lorem ipsum dolor sit (H4)</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque vitae debitis, adipisci natus, accusamus alias nulla aspernatur ipsam reprehenderit nostrum praesentium earum deserunt saepe soluta necessitatibus odit, delectus quisquam quod tempora rerum a, libero quidem numquam doloribus. Quis laborum, nam. Inventore corrupti aliquid tempore, sed quae totam eveniet suscipit quaerat, culpa rem voluptate dolorum veritatis modi. Obcaecati quis laudantium, voluptatibus illum delectus non perspiciatis explicabo, ducimus, consequuntur ratione repellendus magni, voluptatem odit neque quae. Numquam dolores, eum sint quod similique at, facilis, praesentium possimus doloribus veniam architecto recusandae rem ipsam! Sed accusamus laborum voluptate beatae, et in dolore, tempore nobis sapiente laudantium ad rerum cumque cupiditate ex, perspiciatis, officia deserunt. Temporibus dolorem tempora deleniti pariatur eius suscipit sapiente numquam, facere quas quia dolore praesentium inventore nobis, atque illo quidem libero ipsum. Recusandae amet, commodi cum voluptate blanditiis officiis temporibus eos doloremque optio ad neque provident nisi voluptatum ipsam explicabo totam quis a vero maxime rerum tempora dolorem. Aspernatur, doloribus. Ad assumenda provident blanditiis quaerat rerum, repellendus eos vel ducimus quidem id expedita aliquam! Id soluta dolore sit perferendis nostrum saepe, praesentium nam, amet in optio quasi incidunt, cum esse maxime. Suscipit hic esse similique unde nemo, ut quas recusandae expedita dolore sapiente blanditiis facere aliquam quibusdam ex est odio facilis at neque voluptatibus praesentium earum dolor! Ullam id porro architecto, nostrum ducimus et odio? Aliquam cupiditate ipsa, magnam, rerum ut harum quos maiores molestiae quae, non odio minus quod temporibus doloribus recusandae dolorum itaque saepe obcaecati animi ab quaerat error, placeat nostrum eveniet. Perferendis similique consequatur non libero molestias reprehenderit ratione repudiandae blanditiis? Molestias maiores in animi delectus assumenda hic fugiat nihil quibusdam reprehenderit, dolore asperiores minus facere maxime perspiciatis rem repellat aspernatur repudiandae labore porro ipsum veniam et quas odio nisi. Eaque assumenda temporibus ex deserunt asperiores voluptate, vero.</p>


      <h3>TODO</h3>
      <ul>
          <li>Hantera avstånd mellan rubriker när dom ligger direkt under varandra</li>
      </ul>
    
    </Page>
  )
}
